### ISSUE TITLE
TypeError: resample() got an unexpected keyword argument 'how'

### ISSUE THREAD

**Issue by qari** [chrisdev/django-pandas#118]
`
rs_kwargs = {'how': 'sum', 'kind': 'period'}
df = qs.to_timeseries(
        index='created',
        pivot_columns='action',
        values='quantity',
        storage='wide',
        freq='Y',
        rs_kwargs=rs_kwargs
    )
`

After update to last version my code is not working. Why?

**Comment by HashRocketSyntax** [comment]
perhaps it is expecting a positional argument in that first argument slot that how is occupying?

**Comment by aisipos** [comment]
Pandas has removed the `how` argument to DataFrame.resample: https://github.com/pandas-dev/pandas/pull/30139/files#diff-03b380f521c43cf003207b0711bac67fL7731
