### ISSUE TITLE
Possible to release latest dev version to PyPI?

### ISSUE THREAD

**Issue by yanivtoledano** [chrisdev/django-pandas#129]
The current official release does not work well with Django > 3.0 (e.g., field annotations do not work #124). The patch has been merged #126 but has not been released to PyPI.

**Comment by chrisdev** [comment]
Sorry. Was waiting for another contribution butt.... I'll deploy this weekend. Sorry for any inconvenience caused

**Comment by yanivtoledano** [comment]
@chrisdev Thanks! No worries at all - I love this repo and bumped into this issue recently when upgrading our Django version. Appreciate your quick response.

**Comment by yanivtoledano** [comment]
@chrisdev Checking in on this one - I don't believe it has been pushed to PyPI yet. Let me know if you think it may take some time - will find alternative solution in such case!

**Comment by chrisdev** [comment]
@yanivtoledano ok pushed to the pypi and to do some updates for travis coverage etc. Sorry about the delay

**Comment by yanivtoledano** [comment]
@chrisdev - Thanks a lot Chris!

**Comment by benoit9126** [comment]
@chrisdev Sorry to reopen this issue but on [Pypi](https://pypi.org/project/django-pandas/#files), the version 0.6.3 is only available through a "macosx" tar.gz 
Moreover, the structure of this archive does not allow me to install Django Pandas (`/Users/cclarke/Virtualenvs/django-panas-2021/ ...`)

**Comment by chrisdev** [comment]
@yanivtoledano @benoit9126 and everybody else this is embarrassing! I bumped the version number to 0.6.4 and we've uploaded both the wheel and the source versions as usual. I _Yanked__ the previous release on PyPI.  I hope that this bit of carelessness on my part did not cause you a lot of problems. Please accept my apologies. Still have to fix some of the travis build failures but I think it runs on most version of python/django

**Comment by benoit9126** [comment]
@chrisdev Don't worry, we all have trouble with CI/CD... :smile: 

Thank you. I successfully installed the version 0.6.4 on my computer. :+1:
