### ISSUE TITLE
configure github actions (travis tests are no longer running)

### ISSUE THREAD

**Issue by graingert** [chrisdev/django-pandas#140]
I can make a PR for this - but I'll need you to enable GHA for me in the repo

**Comment by chrisdev** [comment]
@graingert GHA are currently set to `Allow all actions: Any action can be used, regardless of who authored it or where it is defined.`

**Comment by graingert** [comment]
> @graingert GHA are currently set to `Allow all actions: Any action can be used, regardless of who authored it or where it is defined.`

for github actions to run there needs to be a workflow on the HEAD of the target repo: https://github.com/chrisdev/django-pandas/pull/144

**Comment by graingert** [comment]
Fixed in https://github.com/chrisdev/django-pandas/pull/145
