### ISSUE TITLE
Pandas 2.1 has a deprecation warning for convert_dtype on read_frame

### ISSUE THREAD

**Issue by bixbyr** [chrisdev/django-pandas#156]
Calling read_frame has a deprecation warning

.../python3.11/site-packages/django_pandas/utils.py:51: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  cache_keys = pk_series.apply(

**Comment by jacksund** [comment]
Just to add to this, I'm seeing another deprecation warning in the `django_pandas.io` module:

> ...\site-packages\django_pandas\io.py:84: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
>   fieldnames = pd.unique(fieldnames)

**Comment by fcoppey** [comment]
is anyone able to update the package with the fixes?

**Comment by bixbyr** [comment]
I wrote a fix which seems to take care of it https://github.com/chrisdev/django-pandas/pull/158. If there are issues let me know.

**Comment by EAItaly** [comment]
Hi, I've a similar question. Using tkinter with Python 3.12.2 under Windows, I receive the message:
"Warning (from warnings module):
 File "C:\Users\\[***]\Python312\Lib\tkinter\\_init-.py", line 1967
    return self.func(*args)
FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``."
So, I think also tkinter needs to be updated. Any comment?
Thanks.

**Comment by bixbyr** [comment]
Now that the fix has been merged is there going to be a release so people can use the latest version via standard python tooling like pip?

**Comment by chrisdev** [comment]
First Release to PyPi version 0.6.7 via the workflow
