### ISSUE TITLE
Handling of django.db.models.query.ValuesQuerySet

### ISSUE THREAD

**Issue by gtnx** [chrisdev/django-pandas#38]
Thoses queries are not properly handled by the library since it uses the values_list method.

For instance, if you define the following queryset
`qs = Object.models.all().values("a", "b").annotate(c=Sum("c"))`

it should return a dataframe such as

       a  b  c
    0  a  b  1

which is not the case.
Do you agree?

**Comment by chrisdev** [comment]
I agree. 
But in most use cases so far we've being using Pandas for aggregation and statistical manipulation and

**Comment by gtnx** [comment]
Done in #37
