### ISSUE TITLE
Django 1.7 support

### ISSUE THREAD

**Issue by victornovais** [chrisdev/django-pandas#41]
Installing django-pandas in a Django 1.7 project I realized that 1.7 version was uninstalled and a 1.6.10 version was installed instead.

Django 1.7 is a problem for django-pandas? Can we change this setup directive to allow django 1.7?

Bellow, link to the code showing the django 1.7 limitation.
https://github.com/chrisdev/django-pandas/blob/master/setup.py#L24

**Comment by chrisdev** [comment]
@victornovais I don't think there is any real issue with allowing Django 1.7 there are some warning about deprecated methods. But everything actually works. 
I just that I haven't had the time to update.  Was planning to hack on this project at PyCon in April 
Do you think you can  submit a pull request to deal with this ??
If not,  I will try to do an release by the end of the week

**Comment by victornovais** [comment]
Sure. I would be happy to.

**Comment by victornovais** [comment]
Done in #42
