### ISSUE TITLE
read_frame columns with model properties

### ISSUE THREAD

**Issue by paulgueltekin** [chrisdev/django-pandas#44]
reading model properies ( with @propery annotated methods of a model ) into DataFrame doesent work yet , because QuerySet.values_list() only works with model fields.

**Comment by miraculixx** [comment]
+1 would much appreciate this feature, in fact calling an arbitrary method on each model instance would be great, such as with a lambda. e.g.

```
# m being the model instance
to_dataframe(qs, map=lambda m : m.some_method())
```

**Comment by chrisdev** [comment]
for now we're closing this

**Comment by ibnbay99** [comment]
Sorry I ask closed issue, but i can't produce earlier codes from @miraculixx ...
How to read model properties with latest pypi, and proper example please... thanks... :)
