### ISSUE TITLE
'Options' object has no attribute 'module_name' at Django 1.8.2

### ISSUE THREAD

**Issue by tubadc** [chrisdev/django-pandas#47]
I'm facing the error:

Django Version:	1.8.2
Exception Type:	AttributeError
Exception Value:	
'Options' object has no attribute 'module_name'

what should I do?

**Comment by coachhippo** [comment]
Hi! According to https://docs.djangoproject.com/en/1.8/internals/deprecation/ its been renamed to model_name. Just update utils.py row 15.
