### ISSUE TITLE
Question: How to get back to a Django data type?

### ISSUE THREAD

**Issue by W7PEA** [chrisdev/django-pandas#54]
Django-Pandas works great. I can then use Pandas to do cool things like .Transpose. But how to get back to a data type that I can use with Django addons that only work with ORM? I don't want to write data back to the model, just pass it off to say DjangoTables2.

This would be a great additional feature!
No one else seems to know either
http://stackoverflow.com/questions/32733958/how-to-use-pandas-dataframe-with-django-tables2

**Comment by chrisdev** [comment]
Great that you found djano-pandas useful @W7PEA :+1: 

I was really unaware of DjangoTables2, but I really wish i knew about it when I was working on the  project that spawned django-pandas :smile:

I've done my similar with smaller summary stats tables including pivot tables for rendering to html. I'm going to sanitise my code examples a bit and post snippets and examples here. 

You and you can tell me if they are helping to solve your problem
We can see if we can hopefully incorporate them into an upcoming release of django-pandas.

People keep telling me to write some blog post with some tips and tricks but ... I suppose I should be more disciplined and take some time out to write.

Also, one of the contributors to this repo @BertrandBordage has a couple of libraries that may be of use to you including https://github.com/BertrandBordage/html_nested_tables

**Comment by W7PEA** [comment]
If you can get me some close enough examples I'm more than happy to help you with some of the wiki pages. I'm more tech pm than dev so that's easy for me. ;)

Thanks a lot!
