### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by ElmerS** [chrisdev/django-pandas#57]
Started working with Django Pandas lately and like it a lot :) 
A few days ago I migrated my Django install to a new server running Django 1.9 and a couple of things broke, like django-pandas. I figured this is partially due to managers.py class DataFrameManager which depends on class PassThroughManager but PassThroughManager has been removed from latest django-utils. Not so sure how to resolve, perhaps something like https://docs.djangoproject.com/en/1.9/topics/db/managers/ (from_queryset). For example:

managers.py
````
from django.db import models
...
...
class BaseManager(models.Manager):
    def manager_only_method(self):
        return

DataFrameManager = BaseManager.from_queryset(DataFrameQuerySet)
```

Apart from that, io.py requires ValuesQuerySet but that has been removed from Django 1.9 as well..

Update io.py to something like:
```

if fieldnames:
        if index_col is not None and index_col not in fieldnames:
            # Add it to the field names if not already there
            fieldnames = tuple(fieldnames) + (index_col,)

        fields = to_fields(qs, fieldnames)
    elif isinstance(qs, django.db.models.query.QuerySet):
        if django.VERSION < (1, 8):
            annotation_field_names = qs.aggregate_names
        else:
            annotation_field_names = list(qs.values().query.annotation_select)

        fieldnames = list(qs.values().query.values_select) + annotation_field_names + list(qs.values().query.extra_select)

        fields = [qs.model._meta.get_field(f) for f in list(qs.values().query.values_select)] + \
                 [None] * (len(annotation_field_names) + len(list(qs.values().query.extra_select)))
    else:
	fields = qs.model._meta.fields
        fieldnames = [f.name for f in fields]

    if isinstance(qs, django.db.models.query.QuerySet):
        vqs = qs.values()
        recs = list(vqs)
```

**Comment by chrisdev** [comment]
Thanks @ElmerS :+1: 
I'm on a short business trip so I'm a bit limited until I return to home base. Is the `PassThroughManager`  also broken by these changes to the QuerySet API? I noticed that it is still referenced in the `model-utils` documentation.  The `PassThroughManager` was a standalone contribution to model_utils so I guess if it can still work with 1.9 we can include it in `django-pandas`
As the

**Comment by Yoshi9143** [comment]
Hey Chris!

Looks like PassThroughManager is removed in model-utils with version 2.4 (http://django-model-utils.readthedocs.org/en/latest/managers.html)

"PassThroughManager was removed in django-model-utils 2.4. Use Django’s built-in QuerySet.as_manager() and/or Manager.from_queryset() utilities instead."

**Comment by chrisdev** [comment]
:+1: @Yoshi9143 . I'm taking a look at this this week!

**Comment by ElmerS** [comment]
@chrisdev Sorry for my late reply, now it was my turn to be off the grid for a while. Anyway, I considered just pasting the PassThroughManager from previous Django_Model_Utils into Django_Pandas but I though, perhaps faulty, that PassThroughManager has been removed for a good reason so I instead of trying to insert a piece of code someone else has discarded for some unknown reason I made the changes to io.py and manager.py (as you can see above or in my fork) and I'm running Django_Pandas now with Django 1.9 for some weeks now... but is really needs some proper testing of course.
