### ISSUE TITLE
django-model-utils 2.4 breaks DataFrameManager because of missing import

### ISSUE THREAD

**Issue by citadelgrad** [chrisdev/django-pandas#61]
If you upgrade to django-model-utils 2.4 the DataFrameManager model manager breaks. It appears that 2.4 remove support for PassThroughManager. The last support django-model-utils was 2.3.1.

**Comment by gbot300** [comment]
Having the same issue

**Comment by chrisdev** [comment]
An update  folks. We've tried but it looks like we going to have to break backwards compatibility. The version that addresses this issue will only be compatible with Django >=1.7
