### ISSUE TITLE
install numpy and pandas in django virtualenv

### ISSUE THREAD

**Issue by micheleeurotech** [chrisdev/django-pandas#64]
I tried to install with pip install numpy and pandas in django virtualenv but it didn't work. Everytime the same response: "Unable to find vcvarsall.bat". I tried to install those libraries in the folder "Scripts" where I normally install the libraries with django.
May someone help me?

**Comment by chrisdev** [comment]
@micheleeurotech. Thanks for reporting this issue. I'm assuming that you are using MS Windows. I found a thread on StackOverFlow that may help http://stackoverflow.com/questions/27670365/python-pip-install-error-unable-to-find-vcvarsall-bat-tried-all-solutions
@Parbhat  We need to setup a windows machine to help with trouble shooting with issues like this

**Comment by micheleeurotech** [comment]
Yes I have Windows 7, Django 1.9 and python 3.5 ... now I look your link.
