### ISSUE TITLE
how to render the pivot table in django template

### ISSUE THREAD

**Issue by mthlvt** [chrisdev/django-pandas#65]
How can I render the dictionary object into an html table in the template?

**Comment by chrisdev** [comment]
@mthlvt I've used ``df.to_html()`` in the view and accessed the context variable as ``{{ pivot_out_as_html|safe }}`` to render the html output in the template. This, believe it our not, gave excellent results! Note the ``to_html`` method takes arguments form formatting numerical output (``formatters`` ), alignment of column contents etc. as explained [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_html.html)

Although I've not personally used it,  I understand that @BertrandBordage has [html_nested_tables](https://github.com/BertrandBordage/html_nested_table) which can apparently handle more complex use cases.

**Comment by BertrandBordage** [comment]
The correct address is https://github.com/BertrandBordage/html_nested_tables
Although it handles more complex cases than pandas, I highly recommend that you use pandas anyway.

**Comment by chrisdev** [comment]
Corrected the URL!
Thanks @BertrandBordage :+1:

**Comment by mthlvt** [comment]
Thanks @chrisdev and @BertrandBordage :smile: 

I simply used the `to_html()` function.

Note to others, you can pass css classes in the view: 
`pt.to_html(classes="table table-striped")`
