### ISSUE TITLE
model._meta.get_all_related_objects_with_model() fails in newer django-versions

### ISSUE THREAD

**Issue by henhuy** [chrisdev/django-pandas#81]
Hello,

I changed the _get_queryset_ method for my model via django.db.models.Manager, like:

    from django.db.models import Model, Manager, IntegerField

    class NewModelManager(Manager):
        def get_queryset(self):
            return super(NewModelManager, self).get_queryset().annotate(
                new_field=F('a') * F('b')
            )
    class NewModel(Model):
        a = IntegerField('First')
        b = IntegerField('Second')

        objects = NewModelManager()

after doing so _readframe()_ does not work with paramter _verbose_ set to _True_ (setting _verbose=False_ works), because function _model._meta.get_all_related_objects_with_model()_ is deprecated:

    qs = cls.objects.all()
    df = read_frame(
        qs,
        fieldnames=['a', 'b', 'new_field'],
        verbose=True
    )

**Comment by henhuy** [comment]
Solved it for myself by editing io.py and utils.py - in my version, if verbose_name is not found fieldname is taken:

**io.py:**

        ...
        for fieldname_part in fieldname.split('__'):
            try:
                field = model._meta.get_field(fieldname_part)
            except django.db.models.fields.FieldDoesNotExist:
                try:
                    rels = model._meta.get_all_related_objects_with_model()
                except AttributeError:
                    yield fieldname
                else:
                    for relobj, _ in rels:
                        if relobj.get_accessor_name() == fieldname_part:
                            field = relobj.field
                            model = field.model
                            break

**utils.py**

    # On top - Import Field:
    from django.db.models import Field

    ...

    def build_update_functions(fieldnames, fields):
        for fieldname, field in zip(fieldnames, fields):
            if not isinstance(field, Field):
                yield fieldname, None
            else:
                if field and field.choices:
                    choices = dict([(k, force_text(v))
                                for k, v in field.flatchoices])
                    yield fieldname, replace_from_choices(choices)

                elif field and field.get_internal_type() == 'ForeignKey':
                     yield fieldname, replace_pk(field.rel.to)


    def update_with_verbose(df, fieldnames, fields):
        for fieldname, function in build_update_functions(fieldnames, fields):
            if function is not None:
                df[fieldname] = function(df[fieldname])

**Comment by chrisdev** [comment]
@henhuy looks nifty. Do you want to send us a pull request?

**Comment by rom1dep** [comment]
Hi there,
Has this been tested against Django 2.0? Using the latest version from pip, which includes the above changes, I get the following trace:

```text
  File "C:\P3\lib\site-packages\django_pandas\io.py", line 125, in read_frame
    update_with_verbose(df, fieldnames, fields)
  File "C:\P3\lib\site-packages\django_pandas\utils.py", line 87, in update_with_verbose
    for fieldname, function in build_update_functions(fieldnames, fields):
  File "C:\P3\lib\site-packages\django_pandas\utils.py", line 73, in build_update_functions
    for fieldname, field in zip(fieldnames, fields):
  File "C:\P3\lib\site-packages\django_pandas\io.py", line 29, in to_fields
    model = field.rel.to
AttributeError: 'ForeignKey' object has no attribute 'rel'
```
app code is something like:
```python3
read_frame(TheModel.objects.all(), fieldnames=['name', 'description', 'foreignattribute__name'])
```

**Comment by chrisdev** [comment]
No @rom1dep we have not tested with Django 2. Would you like to raise this as an issue so someone can send in a PR?
