### ISSUE TITLE
Support for Django 2.0 and above

### ISSUE THREAD

**Issue by chrisdev** [chrisdev/django-pandas#88]
Django 2.0 only supports Python 3.4, 3.5, and 3.6. Django 1.11.x series is the last to support Python 2.7.

**Comment by meiralins** [comment]
@chrisdev , are you working on this already?

**Comment by chrisdev** [comment]
@meiralins I confess that I have not started as yet and would not mind terribly if someone else would start 😄

**Comment by meiralins** [comment]
@chrisdev I have a patch ready, that works for all versions.
I can send a PR.

Also, if we drop support for django<=1.7, the code is simpler and way more readable.

**Comment by meiralins** [comment]
@chrisdev , either option works in my project. Choose one and I shall send a PR.

Django 2.0 remove Fields.rel. If you choose https://github.com/meiralins/django-pandas/commit/2525e27d6bca7f9df5319c37b262ce4c648ea813, I can add comments and refactor the logic.

If we are going to drop for <1.8 I guess https://github.com/meiralins/django-pandas/commit/512aae5538c2661f5c8c609d9178a3a0a45da0e9 is the way to go.

**Comment by chrisdev** [comment]
Many thanks @meiralins, you're a star to be sure! Last time I tried to drop support for the old versions Django, folks were not at all happy. Apparently they were stuck on ancient versions of RHEL which came with Python 2.4. But that was a couple of years ago (I think?).  Surely we can move our threshold up to Django 1.8?  So let's go with [2525e27](https://github.com/meiralins/django-pandas/commit/2525e27d6bca7f9df5319c37b262ce4c648ea813) for now and . 
then we can raise 1.8+ as a separate issue.

**Comment by meiralins** [comment]
Thank you for your work here @chrisdev . When should I expect a new version?

**Comment by chrisdev** [comment]
@meiralins I will try for a release this weekend if things go well Saturday?
