### ISSUE TITLE
to_timeseries() doens't set index's dtype as Datetime... 

### ISSUE THREAD

**Issue by rightx2** [chrisdev/django-pandas#94]
Here is my `Django` model

```
class DailyPrice(StockDataBaseModel):
    df_field_list = [
        'open', 'high', 'low', 'close', 'volume'
    ]
    index_field = 'date'

    date = models.DateField()
    open = models.DecimalField(
        max_digits=15,  # total digits including floating point
        decimal_places=2,
    )
    high = models.DecimalField(
        max_digits=15,
        decimal_places=2,
    )
    low = models.DecimalField(
        max_digits=15,
        decimal_places=2,
    )
    close = models.DecimalField(
        max_digits=15,
        decimal_places=2,
    )
    volume = models.DecimalField(
        max_digits=15,
        decimal_places=2,
    )
```

And retrieve data as `DataFrame`,
```
price_df = price_set.to_timeseries(
    DailyPrice.df_field_list,
    index=DailyPrice.index_field
)
```
And check the index, it shows `object` type.. not `DateTime` or `time-related-datatype`

```
In [2]: price_df.index
Out[2]:
Index([1999-08-11, 1999-08-12, 1999-08-13, 1999-08-16, 1999-08-17, 1999-08-18,
       1999-08-19, 1999-08-20, 1999-08-23, 1999-08-24,
       ...
       2018-03-13, 2018-03-14, 2018-03-15, 2018-03-16, 2018-03-19, 2018-03-20,
       2018-03-21, 2018-03-22, 2018-03-23, 2018-03-26],
      dtype='object', name='date', length=4601)

In [3]: price_df.index.dtype
Out[3]: dtype('O')
```
I think this should be included in the library, don't they?

**Comment by rightx2** [comment]
If you think so, may I send the pull request?

**Comment by chrisdev** [comment]
@rightx2 yes of course you can send a PR 👍 💃

**Comment by rightx2** [comment]
Still can not find what cause it .

**Comment by rightx2** [comment]
I found out !,  If field is `DateField` (not `DateTimeField`), it doesn't work !!

**Comment by rightx2** [comment]
I sent pull request. Check that out please : )

**Comment by osvill** [comment]
Still doesn't work for me after commit `383f6369d9fd139e4695ddab0fb4786f4386ae0c`.

For the method `to_timeseries` if `freq='D'` and `storage='long'` I still get the error message:
 `TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'`

I see the problem in `managers.py line 213`. There is no `index` passed to the `to_dataframe` method  so `df.index = pd.to_datetime(df.index, errors="ignore")` in `io.py line 125` would be ignored. My solution:
Put the `df.index = pd.to_datetime(df.index, errors="ignore")`  in to `managers.py` **before** `if freq is not None:` at `line 233`.

**Comment by osvill** [comment]
Additionally there would occur a `FutureWarning` for the `how` in `.resample()` for the `rs_kwargs`.
